import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
// In a real app, you would wrap this with your state management provider
// import { AuthProvider } from '@/contexts/AuthContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'IAM SaaS Platform',
  description: 'Generated by your expert architect',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <AuthProvider>{children}</AuthProvider> */}
        {children}
      </body>
    </html>
  );
}