server:
  port: "8080"
  mode: "debug"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres" # dummy for dev
  dbname: "iam_saas"
  sslmode: "disable"

jwt:
  # The secret key MUST be set via the JWT_SECRET_KEY environment variable.
  # Use a long, randomly generated string for production.
  secret_key: "752e69e32f8a389bcfa2b2898fece380eee58fd2d22e0337381580d789a4faef" # dummy for dev
  access_token_expiry: 15 # in minutes
  refresh_token_expiry: 10080 # in minutes (7 days)
