server:
  port: "8080"
  mode: "debug"

database:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "postgres"
  dbname: "iam_saas"
  sslmode: "disable"

jwt:
  secret_key: "your_super_secret_key_that_is_long_and_secure"
  access_token_expiry: 15
  refresh_token_expiry: 10080